//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    
    public partial class DoanhThuCacQuy_Result1
    {
        public int Quy { get; set; }
        public Nullable<double> DoanhThu { get; set; }
    }
}
