//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGIAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONGIAO()
        {
            this.CTDGs = new HashSet<CTDG>();
        }
    
        public string MADG { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string MAKH { get; set; }
        public string NGUOINHAN { get; set; }
        public string SDT { get; set; }
        public string SONHA { get; set; }
        public string PHUONGXA { get; set; }
        public Nullable<double> TRIGIA { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDG> CTDGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHUONGXA PHUONGXA1 { get; set; }
    }
}
