//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DONGIAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONGIAO()
        {
            this.CTDGs = new HashSet<CTDG>();
        }
        [Display(Name = "Mã đơn")]            
        public string MADG { get; set; }
        [Display(Name = "Ngày lập")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        [Display(Name = "Khách hàng")]
        public string MAKH { get; set; }
        [Display(Name = "Người nhận")]
        public string NGUOINHAN { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Địa chỉ")]
        public string SONHA { get; set; }
        [Display(Name = "Địa chỉ")]
        public string PHUONGXA { get; set; }
        public Nullable<double> TRIGIA { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDG> CTDGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHUONGXA PHUONGXA1 { get; set; }
    }
}
