//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVIHANHCHINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONVIHANHCHINH()
        {
            this.PHUONGXAs = new HashSet<PHUONGXA>();
            this.QUANHUYENs = new HashSet<QUANHUYEN>();
            this.TINHTHANHs = new HashSet<TINHTHANH>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string full_name_en { get; set; }
        public string short_name { get; set; }
        public string short_name_en { get; set; }
        public string code_name { get; set; }
        public string code_name_en { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUONGXA> PHUONGXAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANHUYEN> QUANHUYENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINHTHANH> TINHTHANHs { get; set; }
    }
}
