//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANHSP
    {
        public int MAHA { get; set; }
        public string MASP { get; set; }
        public string HINHANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
