//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    
    public partial class LocSanPhamTheoGia_Result1
    {
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MACTL_SP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public string MADBC { get; set; }
        public string MAQCDG { get; set; }
        public string ANHDAIDIEN { get; set; }
        public string NOIDUNG { get; set; }
        public string CONGDUNG { get; set; }
        public Nullable<double> TONGDANHGIA { get; set; }
        public Nullable<int> TONKHO { get; set; }
        public string THANHPHAN { get; set; }
        public string DUNGTICH { get; set; }
        public string TRANGTHAI { get; set; }
    }
}
