//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.DONNHAPs = new HashSet<DONNHAP>();
            this.QUYENs = new HashSet<QUYEN>();
        }
    
        public string MANV { get; set; }
        public string TENNV { get; set; }
        public string GIOITINH { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được trống")]
        [RegularExpression(@"^(0|\+84)([0-9]{9}|[0-9]{3}\-[0-9]{3}\-[0-9]{3})$", ErrorMessage = "Hãy nhập số điện thoại hợp lệ")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Mật khẩu thoại không được trống")]
        [StringLength(16, ErrorMessage = "Mật khẩu phải từ 3 đến 16 kí tự", MinimumLength = 3)]
        [RegularExpression(@"^(.{0,7}|[^0-9]*|[^A-Z])$", ErrorMessage = "Hãy nhập mật khẩu hợp lệ")]
        public string MATKHAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONNHAP> DONNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYEN> QUYENs { get; set; }
    }
}
