//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFaceShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHPHAN
    {
        public string MASP { get; set; }
        public string HAMLUONG { get; set; }
        public string TENTP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
